FROM node:22-alpine AS builder
WORKDIR /app

ARG REACT_APP_PROXY_URI
ARG REACT_APP_SERVER_URI
ARG REACT_APP_GOOGLE_CLIENT_ID
ARG REACT_APP_ENCRYPTION_SECRET
ENV REACT_APP_PROXY_URI=$REACT_APP_PROXY_URI
ENV REACT_APP_SERVER_URI=$REACT_APP_SERVER_URI
ENV REACT_APP_GOOGLE_CLIENT_ID=$REACT_APP_GOOGLE_CLIENT_ID
ENV REACT_APP_ENCRYPTION_SECRET=$REACT_APP_ENCRYPTION_SECRET

ENV GENERATE_SOURCEMAP=false
ENV DISABLE_ESLINT_PLUGIN=true

COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:22-alpine
WORKDIR /app

ARG PORT
ENV NODE_ENV=production
ENV PORT=$PORT

RUN npm install -g serve

COPY --from=builder /app/build ./build

EXPOSE ${PORT}
CMD ["serve", "-s", "build"]